# Generated by Django 5.1.4 on 2024-12-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=30)),
                ('comision', models.IntegerField()),
            ],
        ),
    ]
